/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author hvjos
 */
public class DELL extends javax.swing.JFrame {
    private mainMenu menu;
    /**
     * Creates new form DELL
     */
    public DELL() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ManufacturerMB = new javax.swing.JSpinner();
        ManufacturerCPU = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ManufacturerPSU = new javax.swing.JSpinner();
        ManufacturerRAM = new javax.swing.JSpinner();
        ManufacturerGPU = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        Assemblers = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LoadingBarMB = new javax.swing.JProgressBar();
        LoadingBarCPU = new javax.swing.JProgressBar();
        LoadingBarPSU = new javax.swing.JProgressBar();
        LoadingBarRAM = new javax.swing.JProgressBar();
        LoadingBarGPU = new javax.swing.JProgressBar();
        QuantityMB = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        QuantityCPU = new javax.swing.JLabel();
        QuantityRAM = new javax.swing.JLabel();
        QuantityPSU = new javax.swing.JLabel();
        QuantityGPU = new javax.swing.JLabel();
        ManufacturedGPUPCs = new javax.swing.JLabel();
        ManufacturedNormalPCs = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        QuantityMB1 = new javax.swing.JLabel();
        QuantityCPU1 = new javax.swing.JLabel();
        QuantityRAM1 = new javax.swing.JLabel();
        QuantityPSU1 = new javax.swing.JLabel();
        QuantityGPU1 = new javax.swing.JLabel();
        ManufacturedGPUPCs1 = new javax.swing.JLabel();
        ManufacturedNormalPCs1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 39, 84));
        jPanel1.setForeground(new java.awt.Color(51, 68, 255));

        jTextField1.setBackground(new java.awt.Color(50, 39, 84));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("DELL Data");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 223, 219));
        jLabel1.setText("Made by Hurtado, José & Ruiz, Joseph ");

        jPanel2.setBackground(new java.awt.Color(87, 59, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Workers");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MotherBoard Manufacturers");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, -1, -1));
        jPanel2.add(ManufacturerMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 61, -1, -1));
        jPanel2.add(ManufacturerCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 93, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPU Manufacturers");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RAM Manufacturers");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 127, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PSU Manufacturers");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 159, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GPU Manufacturers");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 191, -1, -1));
        jPanel2.add(ManufacturerPSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 157, -1, -1));
        jPanel2.add(ManufacturerRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 125, -1, -1));
        jPanel2.add(ManufacturerGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 189, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Assemblers");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 223, -1, -1));
        jPanel2.add(Assemblers, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 221, -1, -1));

        jPanel3.setBackground(new java.awt.Color(87, 59, 48));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Components in Storage");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MotherBoards");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CPUs");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RAMs");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PSUs");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("GPUs");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, -1, -1));
        jPanel3.add(LoadingBarMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 61, 111, 20));
        jPanel3.add(LoadingBarCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 87, 111, 20));
        jPanel3.add(LoadingBarPSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 139, 111, 20));
        jPanel3.add(LoadingBarRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 113, 111, 20));
        jPanel3.add(LoadingBarGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 165, 111, 20));

        QuantityMB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityMB.setForeground(new java.awt.Color(255, 255, 255));
        QuantityMB.setText("15");
        jPanel3.add(QuantityMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 61, 47, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Normal Computers");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 226, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("GPU Computers");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 252, -1, -1));

        QuantityCPU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityCPU.setForeground(new java.awt.Color(255, 255, 255));
        QuantityCPU.setText("15");
        jPanel3.add(QuantityCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 87, 47, -1));

        QuantityRAM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityRAM.setForeground(new java.awt.Color(255, 255, 255));
        QuantityRAM.setText("15");
        jPanel3.add(QuantityRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 113, 47, -1));

        QuantityPSU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityPSU.setForeground(new java.awt.Color(255, 255, 255));
        QuantityPSU.setText("15");
        jPanel3.add(QuantityPSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 139, 47, -1));

        QuantityGPU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityGPU.setForeground(new java.awt.Color(255, 255, 255));
        QuantityGPU.setText("15");
        jPanel3.add(QuantityGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 165, 47, -1));

        ManufacturedGPUPCs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManufacturedGPUPCs.setForeground(new java.awt.Color(255, 255, 255));
        ManufacturedGPUPCs.setText("15");
        jPanel3.add(ManufacturedGPUPCs, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 252, 47, -1));

        ManufacturedNormalPCs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManufacturedNormalPCs.setForeground(new java.awt.Color(255, 255, 255));
        ManufacturedNormalPCs.setText("15");
        jPanel3.add(ManufacturedNormalPCs, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 226, 47, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Total Manufactured Computers ");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 191, -1, -1));

        jPanel4.setBackground(new java.awt.Color(87, 59, 48));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Status ");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PM");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Director");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Days until Deadline");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 119, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Days passed");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, -1, -1));

        QuantityMB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityMB1.setForeground(new java.awt.Color(255, 255, 255));
        QuantityMB1.setText("Working");
        jPanel4.add(QuantityMB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 61, 69, -1));

        QuantityCPU1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityCPU1.setForeground(new java.awt.Color(255, 255, 255));
        QuantityCPU1.setText("Working");
        jPanel4.add(QuantityCPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 87, 69, -1));

        QuantityRAM1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityRAM1.setForeground(new java.awt.Color(255, 255, 255));
        QuantityRAM1.setText("15");
        jPanel4.add(QuantityRAM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 119, 47, -1));

        QuantityPSU1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityPSU1.setForeground(new java.awt.Color(255, 255, 255));
        QuantityPSU1.setText("15");
        jPanel4.add(QuantityPSU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 145, 47, -1));

        QuantityGPU1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityGPU1.setForeground(new java.awt.Color(255, 255, 255));
        QuantityGPU1.setText("15");
        jPanel4.add(QuantityGPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 165, 47, -1));

        ManufacturedGPUPCs1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManufacturedGPUPCs1.setForeground(new java.awt.Color(255, 255, 255));
        ManufacturedGPUPCs1.setText("15");
        jPanel4.add(ManufacturedGPUPCs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 217, 47, -1));

        ManufacturedNormalPCs1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManufacturedNormalPCs1.setForeground(new java.awt.Color(255, 255, 255));
        ManufacturedNormalPCs1.setText("15");
        jPanel4.add(ManufacturedNormalPCs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 191, 47, -1));

        backButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        backButton.setText("🔙");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(backButton))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(632, 632, 632)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(backButton)
                .addGap(3, 3, 3)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        if (menu==null) {
            menu=new mainMenu();
            menu.setVisible(true);
        } else {
            menu.setVisible(true);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Assemblers;
    private javax.swing.JProgressBar LoadingBarCPU;
    private javax.swing.JProgressBar LoadingBarGPU;
    private javax.swing.JProgressBar LoadingBarMB;
    private javax.swing.JProgressBar LoadingBarPSU;
    private javax.swing.JProgressBar LoadingBarRAM;
    private javax.swing.JLabel ManufacturedGPUPCs;
    private javax.swing.JLabel ManufacturedGPUPCs1;
    private javax.swing.JLabel ManufacturedNormalPCs;
    private javax.swing.JLabel ManufacturedNormalPCs1;
    private javax.swing.JSpinner ManufacturerCPU;
    private javax.swing.JSpinner ManufacturerGPU;
    private javax.swing.JSpinner ManufacturerMB;
    private javax.swing.JSpinner ManufacturerPSU;
    private javax.swing.JSpinner ManufacturerRAM;
    private javax.swing.JLabel QuantityCPU;
    private javax.swing.JLabel QuantityCPU1;
    private javax.swing.JLabel QuantityGPU;
    private javax.swing.JLabel QuantityGPU1;
    private javax.swing.JLabel QuantityMB;
    private javax.swing.JLabel QuantityMB1;
    private javax.swing.JLabel QuantityPSU;
    private javax.swing.JLabel QuantityPSU1;
    private javax.swing.JLabel QuantityRAM;
    private javax.swing.JLabel QuantityRAM1;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
